import mongoose, { Schema, Document } from 'mongoose';

export interface IReminder extends Document {
  userId: string;
  eventId?: mongoose.Types.ObjectId; // Reference to the event that triggered this

  // What to remind about
  type: 'event_before' | 'event_after' | 'goal_checkin' | 'periodic_checkin';
  title: string; // "Job interview at Google"
  context: string; // Original context from conversation

  // When to send
  scheduledFor: Date;

  // Reminder content (generated by LLM when due)
  generatedMessage?: string;

  // Status tracking
  status: 'pending' | 'sent' | 'dismissed' | 'snoozed';
  sentAt?: Date;

  // For recurring reminders (like goal check-ins)
  recurring: boolean;
  recurringInterval?: 'daily' | 'weekly' | 'biweekly' | 'monthly';
  nextOccurrence?: Date;

  // Priority (affects notification timing)
  priority: 'low' | 'medium' | 'high';

  // Metadata
  metadata?: {
    eventType?: string; // job_interview, trip, deadline, etc.
    entities?: string[]; // Google, Paris, Max (dog), etc.
    originalDate?: Date; // The date of the event itself
    emotion?: string; // How they felt (excited, nervous, stressed)
  };

  createdAt: Date;
  updatedAt: Date;
}

const reminderSchema = new Schema<IReminder>(
  {
    userId: { type: String, required: true, index: true },
    eventId: { type: Schema.Types.ObjectId, ref: 'Event' },

    type: {
      type: String,
      enum: ['event_before', 'event_after', 'goal_checkin', 'periodic_checkin'],
      required: true,
    },
    title: { type: String, required: true },
    context: { type: String, required: true },

    scheduledFor: { type: Date, required: true, index: true },

    generatedMessage: String,

    status: {
      type: String,
      enum: ['pending', 'sent', 'dismissed', 'snoozed'],
      default: 'pending',
      index: true,
    },
    sentAt: Date,

    recurring: { type: Boolean, default: false },
    recurringInterval: {
      type: String,
      enum: ['daily', 'weekly', 'biweekly', 'monthly'],
    },
    nextOccurrence: Date,

    priority: {
      type: String,
      enum: ['low', 'medium', 'high'],
      default: 'medium',
    },

    metadata: {
      eventType: String,
      entities: [String],
      originalDate: Date,
      emotion: String,
    },
  },
  { timestamps: true }
);

// Compound indexes for efficient queries
reminderSchema.index({ userId: 1, status: 1, scheduledFor: 1 });
reminderSchema.index({ status: 1, scheduledFor: 1 }); // For global scheduler

export const Reminder = mongoose.model<IReminder>('Reminder', reminderSchema);
